name: Run TMDB Script

on:
  workflow_dispatch:  # lets you trigger it manually from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-22.04

    env:  # Inject secrets as environment variables
      USER: ${{ secrets.user }}
      PASSWORD: ${{ secrets.password }}
      ACCOUNT: ${{ secrets.account }}
      API_KEY: ${{ secrets.api_key }}
      API_TOKEN: ${{ secrets.api_token }}
      WAREHOUSE: ${{ secrets.warehouse }}
      DATABASE: ${{ secrets.database }}
      SCHEMA: ${{ secrets.schema }}
      SCHEMA_REPORTING : ${{ secrets.schema_reporting }} 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TMDB ingestion script
        run: |
          python fetch_tmdb_metadata.py
